#!/bin/bash

echo "==========================================="
echo "bench_M1_sphincs-shake-128f-simple_BAS"
sudo bin/bench_M1_sphincs-shake-128f-simple_BAS
echo "==========================================="
echo "bench_M1_sphincs-shake-128f-simple_COTHANV8"
sudo bin/bench_M1_sphincs-shake-128f-simple_COTHANV8
echo "==========================================="
echo "bench_M1_sphincs-shake-128f-simple_COTHANV84"
sudo bin/bench_M1_sphincs-shake-128f-simple_COTHANV84
echo "==========================================="
echo "bench_M1_sphincs-shake-128s-simple_BAS"
sudo bin/bench_M1_sphincs-shake-128s-simple_BAS
echo "==========================================="
echo "bench_M1_sphincs-shake-128s-simple_COTHANV8"
sudo bin/bench_M1_sphincs-shake-128s-simple_COTHANV8
echo "==========================================="
echo "bench_M1_sphincs-shake-128s-simple_COTHANV84"
sudo bin/bench_M1_sphincs-shake-128s-simple_COTHANV84
echo "==========================================="
echo "bench_M1_sphincs-shake-192f-simple_BAS"
sudo bin/bench_M1_sphincs-shake-192f-simple_BAS
echo "==========================================="
echo "bench_M1_sphincs-shake-192f-simple_COTHANV8"
sudo bin/bench_M1_sphincs-shake-192f-simple_COTHANV8
echo "==========================================="
echo "bench_M1_sphincs-shake-192f-simple_COTHANV84"
sudo bin/bench_M1_sphincs-shake-192f-simple_COTHANV84
echo "==========================================="
echo "bench_M1_sphincs-shake-192s-simple_BAS"
sudo bin/bench_M1_sphincs-shake-192s-simple_BAS
echo "==========================================="
echo "bench_M1_sphincs-shake-192s-simple_COTHANV8"
sudo bin/bench_M1_sphincs-shake-192s-simple_COTHANV8
echo "==========================================="
echo "bench_M1_sphincs-shake-192s-simple_COTHANV84"
sudo bin/bench_M1_sphincs-shake-192s-simple_COTHANV84
echo "==========================================="
echo "bench_M1_sphincs-shake-256f-simple_BAS"
sudo bin/bench_M1_sphincs-shake-256f-simple_BAS
echo "==========================================="
echo "bench_M1_sphincs-shake-256f-simple_COTHANV8"
sudo bin/bench_M1_sphincs-shake-256f-simple_COTHANV8
echo "==========================================="
echo "bench_M1_sphincs-shake-256f-simple_COTHANV84"
sudo bin/bench_M1_sphincs-shake-256f-simple_COTHANV84
echo "==========================================="
echo "bench_M1_sphincs-shake-256s-simple_BAS"
sudo bin/bench_M1_sphincs-shake-256s-simple_BAS
echo "==========================================="
echo "bench_M1_sphincs-shake-256s-simple_COTHANV8"
sudo bin/bench_M1_sphincs-shake-256s-simple_COTHANV8
echo "==========================================="
echo "bench_M1_sphincs-shake-256s-simple_COTHANV84"
sudo bin/bench_M1_sphincs-shake-256s-simple_COTHANV84
