#!/bin/bash

echo "=========================================="
echo "bin/bench_M1_sphincs-shake-128f-simple_x3"
sudo bin/bench_M1_sphincs-shake-128f-simple_x3
echo "=========================================="
echo "bin/bench_M1_sphincs-shake-128f-simple_x4"
sudo bin/bench_M1_sphincs-shake-128f-simple_x4
echo "=========================================="
echo "bin/bench_M1_sphincs-shake-128f-simple_x5"
sudo bin/bench_M1_sphincs-shake-128f-simple_x5
echo "=========================================="
echo "bin/bench_M1_sphincs-shake-128s-simple_x3"
sudo bin/bench_M1_sphincs-shake-128s-simple_x3
echo "=========================================="
echo "bin/bench_M1_sphincs-shake-128s-simple_x4"
sudo bin/bench_M1_sphincs-shake-128s-simple_x4
echo "=========================================="
echo "bin/bench_M1_sphincs-shake-128s-simple_x5"
sudo bin/bench_M1_sphincs-shake-128s-simple_x5
echo "=========================================="
echo "bin/bench_M1_sphincs-shake-192f-simple_x3"
sudo bin/bench_M1_sphincs-shake-192f-simple_x3
echo "=========================================="
echo "bin/bench_M1_sphincs-shake-192f-simple_x4"
sudo bin/bench_M1_sphincs-shake-192f-simple_x4
echo "=========================================="
echo "bin/bench_M1_sphincs-shake-192f-simple_x5"
sudo bin/bench_M1_sphincs-shake-192f-simple_x5
echo "=========================================="
echo "bin/bench_M1_sphincs-shake-192s-simple_x3"
sudo bin/bench_M1_sphincs-shake-192s-simple_x3
echo "=========================================="
echo "bin/bench_M1_sphincs-shake-192s-simple_x4"
sudo bin/bench_M1_sphincs-shake-192s-simple_x4
echo "=========================================="
echo "bin/bench_M1_sphincs-shake-192s-simple_x5"
sudo bin/bench_M1_sphincs-shake-192s-simple_x5
echo "=========================================="
echo "bin/bench_M1_sphincs-shake-256f-simple_x3"
sudo bin/bench_M1_sphincs-shake-256f-simple_x3
echo "=========================================="
echo "bin/bench_M1_sphincs-shake-256f-simple_x4"
sudo bin/bench_M1_sphincs-shake-256f-simple_x4
echo "=========================================="
echo "bin/bench_M1_sphincs-shake-256f-simple_x5"
sudo bin/bench_M1_sphincs-shake-256f-simple_x5
echo "=========================================="
echo "bin/bench_M1_sphincs-shake-256s-simple_x3"
sudo bin/bench_M1_sphincs-shake-256s-simple_x3
echo "=========================================="
echo "bin/bench_M1_sphincs-shake-256s-simple_x4"
sudo bin/bench_M1_sphincs-shake-256s-simple_x4
echo "=========================================="
echo "bin/bench_M1_sphincs-shake-256s-simple_x5"
sudo bin/bench_M1_sphincs-shake-256s-simple_x5